# Generated by Django 5.1.15 on 2026-09-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_delivery_time_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GOAL_ASSIGNED', 'Goal Assigned'), ('EVIDENCE_REVIEWED', 'Evidence Reviewed'), ('APPRAISAL_PUBLISHED', 'Appraisal Published'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('DEADLINE_APPROACHING', 'Deadline Approaching'), ('MENTOR_FEEDBACK', 'Mentor Feedback Published'), ('SELF_APPRAISAL_OPENED', 'Self-Appraisal Opened'), ('FORM_PUBLISHED', 'Form Published'), ('EVALUATION_CYCLE_UPDATE', 'Evaluation Cycle Update'), ('SYSTEM', 'System Alert')], default='SYSTEM', max_length=50),
        ),
    ]
