# Generated by Django 5.1.15 on 2026-09-27 20:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeeprofile_birth_place_and_more'),
        ('goals', '0001_initial'),
        ('organization', '0003_financialyear_performancecategory_permission_and_more'),
        ('performance', '0003_performanceimprovementplan_recognitionreward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KpiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'KPI Category',
                'verbose_name_plural': 'KPI Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GoalSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('LOCKED', 'Locked'), ('SCORED', 'Scored'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('version', models.IntegerField(default=1)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_goal_sets', to=settings.AUTH_USER_MODEL)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_sets', to='performance.performancecycle')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_sets', to='employees.employeeprofile')),
            ],
            options={
                'verbose_name': 'Goal Set',
                'verbose_name_plural': 'Goal Sets',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KpiAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('change_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_audits', to='employees.employeeprofile')),
                ('goal_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='goals.goalset')),
            ],
            options={
                'verbose_name': 'KPI Audit Trail',
                'verbose_name_plural': 'KPI Audit Trails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='%', max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('current_progress', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('weight_percent', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('is_compliance', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_goal_items', to=settings.AUTH_USER_MODEL)),
                ('goal_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='goals.goalset')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_items', to='goals.kpicategory')),
            ],
            options={
                'verbose_name': 'Goal Item',
                'verbose_name_plural': 'Goal Items',
            },
        ),
        migrations.CreateModel(
            name='KpiLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_libraries', to='organization.position')),
                ('target_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_libraries', to='organization.joblevel')),
            ],
            options={
                'verbose_name': 'KPI Library',
                'verbose_name_plural': 'KPI Libraries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='goalset',
            name='library',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_sets', to='goals.kpilibrary'),
        ),
        migrations.CreateModel(
            name='KpiLibraryDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_title', models.CharField(max_length=255)),
                ('unit', models.CharField(default='%', max_length=50)),
                ('target_value', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=12)),
                ('weight_percent', models.IntegerField(default=20)),
                ('is_compliance', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='library_details', to='goals.kpicategory')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='goals.kpilibrary')),
            ],
            options={
                'verbose_name': 'KPI Library Detail',
                'verbose_name_plural': 'KPI Library Details',
            },
        ),
        migrations.CreateModel(
            name='KpiProgressEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('progress_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('evidence_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='goals.goalitem')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KPI Progress Entry',
                'verbose_name_plural': 'KPI Progress Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='goalset',
            unique_together={('employee', 'cycle')},
        ),
    ]
