# Generated by Django 5.1.15 on 2026-09-28 05:10

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_performanceimprovementplan_recognitionreward'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationcriterion',
            options={'ordering': ['-weight', 'name'], 'verbose_name': 'Evaluation Criterion', 'verbose_name_plural': 'Evaluation Criteria'},
        ),
        migrations.AddField(
            model_name='evaluationcriterion',
            name='cycle',
            field=models.ForeignKey(blank=True, help_text='Specific cycle this criterion belongs to, or null for global/cohort default', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='performance.performancecycle'),
        ),
        migrations.AddField(
            model_name='performancecycle',
            name='goals_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Weight in percentage for Goals & Deliverables component (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='performancecycle',
            name='manager_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('40.00'), help_text='Weight in percentage for Mentor/Manager Evaluation component (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddField(
            model_name='performancecycle',
            name='self_weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Weight in percentage for Intern Self Assessment component (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='evaluationcriterion',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
